# This workflow will run when the pull request is created, edited, updated with new commits and reopened

name: Pull Request Template Validator
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - qa

jobs:
  ok_ok:
    name: Validajting PR Body
    runs-on: ubuntu-latest  
    steps:
    - name: base64 encode the staging gcr sa
      id: base64-staging-gcr
      shell: bash
      run:
        echo "::set-output name=STAGING_GCR_SA_BASE64::$(echo "${{ github.event.pull_request.body }}" | python -m base64 -e)"
  pr_body_validator:
    name: Validating PR Body
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18   
      - name: Get result
        run: |
           echo ${{ steps.base64-staging-gcr.outputs.STAGING_GCR_SA_BASE64 }}
           echo "${{ toJson(github.event.pull_request) }}"  
           node ./.github/scripts/test.js '${{ github.event.pull_request.body }}'
