name: Theme-Generator - Agency-Dispatch
on:
  pull_request:
    types:
      - closed
    branches: 
      - main


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 100
        echo "${{ github.event.pull_request.head_ref }}"
        echo "${{ github.event.pull_request.merge_commit_sha }}"
        echo The PR was merged
