name: Caching npm packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      id: cache-nodeq-modules
      uses: actions/cache@v2
      env:
        cache-name: cache-nodeq-modules
      with:
        # caching node_modules
        path: sample/node_modules
        key: ${{ runner.os }}-builds-${{ env.cache-name }}-${{ hashFiles('sample/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-builds-${{ env.cache-name }}-
          ${{ runner.os }}-builds-
          ${{ runner.os }}-
    - name: Install Dependencies
      if: steps.cache-nodeq-modules.outputs.cache-hit != 'true'
      run: cd sample && npm i --legacy-peer-deps
    - name: Run Script
      run: cat package.json
    - name: Echo Node
      run: cd sample && npm run start1
