name: Theme-Generator - Agency-Dispatch
on:
  pull_request:
    types:
      - closed
    branches: 
      - main


concurrency:
  group: stage123
  cancel-in-progress: false


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 10
        echo "${{ github.event.pull_request.pr_title }}"
        echo "${{ github.run_id }}"
        echo "${{ github.event.pull_request.merge_commit_sha }}"
        echo The PR was merged
