# This workflow will run after the pull request is merged
# This workflow will update the platform version and will create release tag

name: Platform Versioning
on:
  pull_request:
    types:
      - closed
    branches:
      - qa

jobs:
  validate-branch:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check if the branch name conforms with the branch naming convention
        run: |
          echo "${{ github.event.pull_request.head_ref }}"
          node ./.github/scripts/test.js ${{ github.event.pull_request.head_ref }}
