name: axe-scan-dispatch
on:
  workflow_dispatch:

jobs:
  execute-axe-scan:
    name: start axe scan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: "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"
          repository: robinatwork1999/product-commerce
          event-type: trigger
          client-payload: '{"brandName": "robin"}'
