name: Theme-Generator - Agency-Dispatch
on:
  pull_request:
    types: 
      - closed
    branches: 
     - main
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'PR Merged'
