name: axe-scan-dispatch
on:
  workflow_dispatch:

jobs:
  execute-axe-scan:
    name: start axe scan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: robinatwork1999/product-commerce
          event-type: trigger
          client-payload: '{"environment": "${"file-to-read":"robin"}'
