# This workflow will run when the pull request is created, edited, updated with new commits and reopened

name: Pull Request Template Validator
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - qa

jobs:
  pr_body_validator:
    name: Validating PR Body
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Validate PR Body"
        run: |
          $quoteEncodeVal=#39;
          $encodedBody=$(echo "${{ github.event.pull_request.body }}" | sed "s/'/$quoteEncodeVal/g")
          node ./.github/scripts/test.js "$encodedBody"
