# This workflow will run after the pull request is merged
# This workflow will update the platform version and will create release tag

name: Platform Versioning
on: 
  pull_request:
    types:
      - opened
      - edited

  issue_comment:
    types:
      - created
      - edited

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
