# This workflow will run after the pull request is merged
# This workflow will update the platform version and will create release tag

name: Platform Versioning
on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - qa 

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    name: PR comment
    steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Check if the user is a allowed to run the workflow
              run: |
                  node ./.github/scripts/test.js "${{ github.event.pull_request.body }}"
            - name: Other variables with ENV
              run: |
                echo "Commits:" $COMMITS
                echo "Message:" $MESSAGE
                echo "Author Email:" $(echo $AUTHOR | jq -r '.body')
              env:
                AUTHOR: ${{ toJSON(github.event.pull_request) }}
