name: Caching npm packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Cache node modules
      id: cache-nodeq-modules
      uses: actions/cache@v2
      env:
        cache-name: cache-nodeq-modules
      with:
        # caching node_modules
        path: sample/node_modules
        key: ${{ runner.os }}-builds-${{ env.cache-name }}-${{ hashFiles('sample/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-builds-${{ env.cache-name }}-
          ${{ runner.os }}-builds-
          ${{ runner.os }}-
    - name: Install Dependencies
      if: steps.cache-nodeq-modules.outputs.cache-hit != 'true'
      run: cd sample && npm i --legacy-peer-deps
    - name: Echoooo
      run: echo "${{ toJSON(github) }}"
    - name: ok  
      run: | 
          cat file1.txt
          date > file1.txt
          git add file1.txt
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git commit -m "updated file1"
          git push
    - name: Echoooo
      run: echo "${{ toJSON(github) }}"          
    - name: newok   
      run: | 
          cat file1.txt

