name: axe-scan-dispatch
on:
  workflow_dispatch:

jobs:
  execute-axe-scan:
    name: start axe scan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: "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"
          repository: robinatwork1999/product-commerce
          event-type: trigger
          client-payload: '{"brandName": "robin"}'
