# This workflow will run after the pull request is merged
# This workflow will update the platform version and will create release tag

name: Platform Versioning
on:
  pull_request:
    types:
      - closed
    branches:
      - qa

jobs:
  branch-filter:
    name: Looking For Automation PR
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.head.ref, 'feature/automation-update') }}
    steps:
    - name: "Print Current Source Branch"
      run: echo "Pull Request Source Branch ${{ github.event.pull_request.head.ref }}"
    
  wait-for-concurrency:
    name: Waiting For Previous Active Job(s) To Finish
    needs: branch-filter
    runs-on: ubuntu-latest
    steps:
     - name: "check data"
       run: echo "here"

  update-version:
    runs-on: ubuntu-latest
    needs: wait-for-concurrency
    steps:
     - name: "check data"
       run: echo "here"
