# This is a workflow used by developers to sync their changes with WhiteLabel/Showcase For Testing Purpose

name: Development Generator

on:
    workflow_dispatch:
        inputs:
            choice:
                type: choice
                description: Select Brand
                options:
                    - whitelabel
                    - showcase
                    - test

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                ref: 21
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Setup configurations
              run: |
                  echo "${{ github.ref }}"

