name: axe-scan-dispatch
on:
  workflow_dispatch:

jobs:
  execute-axe-scan:
    name: start axe scan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatchs    
        run: sleep 50 
