name: axe-scan-dispatch
on:
  workflow_dispatch:

jobs:
  execute-axe-scan:
    name: start axe scan
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.TOKEN }}
          repository: robinatwork1999/product-commerce
          event-type: trigger
          client-payload: '{"brandName": "robin"}'
      - name: Invoke workflow in another repo with inputs
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Theme-Generator - Agency-Dispatch
          repo: robinatwork1999/product-commerce
          token: ${{ secrets.TOKEN }}
          inputs: '{ "message": "blah blah", "debug": true }'
          wait-for-completion: 'true'
