# This workflow will run after the pull request is merged
# This workflow will update the platform version and will create release tag

name: Platform Versioning
on:
  pull_request:
    types:
      - closed
    branches:
      - qa

jobs:
  wait-for-concurrency:
    name: Waiting For Previous Active Job(s) To Finish
    if: startsWith(github.event.pull_request.head.ref, 'features/automation')
    runs-on: ubuntu-latest
    steps:
     - name: "check data"
       run: echo "here"

  update-version:
    runs-on: ubuntu-latest
    needs: wait-for-concurrency
    steps:
     - name: "check data"
       run: echo "here"
